### ISSUE TITLE
npm install error on Node 4.1.1

### ISSUE THREAD

**Issue by AlexAugot** [TooTallNate/ref-union#3]
Hi,

I'm having a problem installing ref-union using npm on the latest version of Node (4.1.1).  I was previously using it with 0.12 and had no problems, but after the update I noticed I was getting build errors in some of my modules that rely on ref-union.  Trying to it install it using npm produces the errors below:
```
npm install ref-union

> ref@0.3.5 install D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref
> node-gyp rebuild


D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
d:\app\nodejs\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan_implementation_12_inl.h(172): error C2660: 'v8::Signature::New': function does not take 4 arguments [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(167): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)': function template has already been defined [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
  D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(160): note: see declaration of '_NanEnsureLocal'
D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(500): error C3083: 'smalloc': the symbol to the left of a '::' must be a type [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(500): error C2039: 'FreeCallback': is not a member of 'node' [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
  D:\Users\aaugot\.node-gyp\4.1.1\include\node\node_object_wrap.h(8): note: see declaration of 'node'
D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(500): error C2061: syntax error: identifier 'FreeCallback' [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(504): error C2065: 'callback': undeclared identifier [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(504): error C2065: 'hint': undeclared identifier [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(511): error C2665: 'node::Buffer::New': none of the 4 overloads could convert all the argument types [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
  D:\Users\aaugot\.node-gyp\4.1.1\include\node\node_buffer.h(43): note: could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
  D:\Users\aaugot\.node-gyp\4.1.1\include\node\node_buffer.h(31): note: or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
  D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(511): note: while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(515): error C2440: 'return': cannot convert from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>' [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
  D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(515): note: No constructor could take the source type, or constructor overload resolution was ambiguous
D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(522): error C2039: 'Use': is not a member of 'node::Buffer' [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
  D:\Users\aaugot\.node-gyp\4.1.1\include\node\node_buffer.h(8): note: see declaration of 'node::Buffer'
D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\node_modules\nan\nan.h(522): error C3861: 'Use': identifier not found [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
..\src\binding.cc(154): error C2661: 'NanNewBufferHandle': no overloaded function takes 4 arguments [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
..\src\binding.cc(271): error C2661: 'NanNewBufferHandle': no overloaded function takes 4 arguments [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
..\src\binding.cc(518): error C2661: 'NanNewBufferHandle': no overloaded function takes 4 arguments [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
..\src\binding.cc(565): error C2661: 'NanNewBufferHandle': no overloaded function takes 4 arguments [D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\app\NodeJS\modules\app-ffi\app-ffi\node_modules\ref-union\node_modules\ref
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ref-union"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! ref@0.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@0.3.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\app\NodeJS\modules\app-ffi\app-ffi\npm-debug.log
```
Error seems to say it's a problem with ref, but I'm also using both ref and ref-struct and don't have any issues using npm to install them.

I've tried running `npm cache clean` but that doesn't seem to have any effect. I don't have any issue if I update from git directly by running `npm install git://github.com/TooTallNate/ref-union`, but i still get build failures downstream when it tries to run `npm install ref-union` again.

Any idea what could be causing this issue?

Thanks

**Comment by TooTallNate** [comment]
Can you try out v1.0.0 of ref-union on npm (published just now)?

**Comment by AlexAugot** [comment]
Seems to be working, ref 1.0.0 gets pulled down instead of 0.3.5.

Thanks for the quick response!
